-- Real order base for WhatsApp-assisted checkout.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'pending',
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  delivery_method text not null,
  delivery_address text,
  delivery_city text,
  delivery_province text,
  postal_code text,
  customer_notes text,
  subtotal integer not null,
  shipping_cost integer not null default 0,
  discount_amount integer not null default 0,
  total integer not null,
  currency text not null default 'ARS',
  source text not null default 'web',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_customer_name_not_empty check (length(btrim(customer_name)) > 0),
  constraint orders_customer_phone_not_empty check (length(btrim(customer_phone)) > 0),
  constraint orders_status_allowed check (
    status in ('pending', 'confirmed', 'preparing', 'ready', 'shipped', 'delivered', 'cancelled')
  ),
  constraint orders_delivery_method_allowed check (
    delivery_method in ('moto_amba', 'correo_argentino', 'retiro')
  ),
  constraint orders_currency_allowed check (currency = 'ARS'),
  constraint orders_subtotal_non_negative check (subtotal >= 0),
  constraint orders_shipping_cost_non_negative check (shipping_cost >= 0),
  constraint orders_discount_amount_non_negative check (discount_amount >= 0),
  constraint orders_total_consistent check (total = subtotal + shipping_cost - discount_amount),
  constraint orders_total_non_negative check (total >= 0)
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  product_slug text,
  unit_price integer not null,
  quantity integer not null,
  line_total integer not null,
  selected_color text,
  selected_compatibility text,
  image_url text,
  created_at timestamptz not null default now(),
  constraint order_items_product_name_not_empty check (length(btrim(product_name)) > 0),
  constraint order_items_unit_price_non_negative check (unit_price >= 0),
  constraint order_items_quantity_positive check (quantity > 0 and quantity <= 99),
  constraint order_items_line_total_consistent check (line_total = unit_price * quantity),
  constraint order_items_line_total_non_negative check (line_total >= 0)
);

create table if not exists public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  previous_status text,
  new_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  constraint order_status_history_previous_status_allowed check (
    previous_status is null or previous_status in (
      'pending', 'confirmed', 'preparing', 'ready', 'shipped', 'delivered', 'cancelled'
    )
  ),
  constraint order_status_history_new_status_allowed check (
    new_status in ('pending', 'confirmed', 'preparing', 'ready', 'shipped', 'delivered', 'cancelled')
  )
);

create index if not exists orders_user_id_idx on public.orders (user_id);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_order_number_idx on public.orders (order_number);
create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists order_status_history_order_created_at_idx
on public.order_status_history (order_id, created_at);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;

revoke all on table public.orders from public;
revoke all on table public.orders from anon;
revoke all on table public.orders from authenticated;
grant select on table public.orders to authenticated;

revoke all on table public.order_items from public;
revoke all on table public.order_items from anon;
revoke all on table public.order_items from authenticated;
grant select on table public.order_items to authenticated;

revoke all on table public.order_status_history from public;
revoke all on table public.order_status_history from anon;
revoke all on table public.order_status_history from authenticated;
grant select on table public.order_status_history to authenticated;

drop policy if exists "Users can read their own orders" on public.orders;
create policy "Users can read their own orders"
on public.orders
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Admins can read all orders" on public.orders;
create policy "Admins can read all orders"
on public.orders
for select
to authenticated
using ((select public.has_admin_access()));

drop policy if exists "Users can read their own order items" on public.order_items;
create policy "Users can read their own order items"
on public.order_items
for select
to authenticated
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can read all order items" on public.order_items;
create policy "Admins can read all order items"
on public.order_items
for select
to authenticated
using ((select public.has_admin_access()));

drop policy if exists "Users can read their own order history" on public.order_status_history;
create policy "Users can read their own order history"
on public.order_status_history
for select
to authenticated
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_status_history.order_id
      and orders.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins can read all order history" on public.order_status_history;
create policy "Admins can read all order history"
on public.order_status_history
for select
to authenticated
using ((select public.has_admin_access()));

create or replace function public.set_order_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_order_updated_at on public.orders;
create trigger set_order_updated_at
before update on public.orders
for each row
execute function public.set_order_updated_at();

create or replace function public.create_order(order_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid;
  customer_name_value text;
  customer_email_value text;
  customer_phone_value text;
  delivery_method_value text;
  delivery_address_value text;
  delivery_city_value text;
  delivery_province_value text;
  postal_code_value text;
  customer_notes_value text;
  items_value jsonb;
  item_value jsonb;
  product_record public.products%rowtype;
  order_id_value uuid;
  order_number_value bigint;
  product_id_value uuid;
  quantity_value integer;
  selected_color_value text;
  selected_compatibility_value text;
  subtotal_value integer := 0;
  shipping_cost_value integer := 0;
  line_total_value integer;
  created_items jsonb := '[]'::jsonb;
begin
  current_user_id := (select auth.uid());
  customer_name_value := left(btrim(coalesce(order_payload ->> 'customerName', '')), 160);
  customer_email_value := nullif(left(btrim(coalesce(order_payload ->> 'customerEmail', '')), 180), '');
  customer_phone_value := left(btrim(coalesce(order_payload ->> 'customerPhone', '')), 60);
  delivery_method_value := left(btrim(coalesce(order_payload ->> 'deliveryMethod', '')), 40);
  delivery_address_value := nullif(left(btrim(coalesce(order_payload ->> 'deliveryAddress', '')), 220), '');
  delivery_city_value := nullif(left(btrim(coalesce(order_payload ->> 'deliveryCity', '')), 120), '');
  delivery_province_value := nullif(left(btrim(coalesce(order_payload ->> 'deliveryProvince', '')), 120), '');
  postal_code_value := nullif(left(btrim(coalesce(order_payload ->> 'postalCode', '')), 24), '');
  customer_notes_value := nullif(left(btrim(coalesce(order_payload ->> 'customerNotes', '')), 500), '');
  items_value := coalesce(order_payload -> 'items', '[]'::jsonb);

  if length(customer_name_value) = 0 then
    raise exception 'invalid_customer_name';
  end if;

  if length(customer_phone_value) = 0 then
    raise exception 'invalid_customer_phone';
  end if;

  if delivery_method_value not in ('moto_amba', 'correo_argentino', 'retiro') then
    raise exception 'invalid_delivery_method';
  end if;

  if jsonb_typeof(items_value) <> 'array' or jsonb_array_length(items_value) = 0 then
    raise exception 'empty_cart';
  end if;

  if jsonb_array_length(items_value) > 50 then
    raise exception 'too_many_items';
  end if;

  shipping_cost_value := case when delivery_method_value = 'moto_amba' then 5000 else 0 end;

  insert into public.orders (
    user_id,
    customer_name,
    customer_email,
    customer_phone,
    delivery_method,
    delivery_address,
    delivery_city,
    delivery_province,
    postal_code,
    customer_notes,
    subtotal,
    shipping_cost,
    discount_amount,
    total,
    currency,
    source
  )
  values (
    current_user_id,
    customer_name_value,
    customer_email_value,
    customer_phone_value,
    delivery_method_value,
    delivery_address_value,
    delivery_city_value,
    delivery_province_value,
    postal_code_value,
    customer_notes_value,
    0,
    shipping_cost_value,
    0,
    shipping_cost_value,
    'ARS',
    'web'
  )
  returning id, order_number into order_id_value, order_number_value;

  for item_value in select * from jsonb_array_elements(items_value)
  loop
    begin
      product_id_value := (item_value ->> 'productId')::uuid;
    exception when others then
      raise exception 'invalid_product';
    end;

    quantity_value := floor(coalesce((item_value ->> 'quantity')::numeric, 0))::integer;
    selected_color_value := nullif(left(btrim(coalesce(item_value ->> 'selectedColor', '')), 80), '');
    selected_compatibility_value := nullif(left(btrim(coalesce(item_value ->> 'selectedCompatibility', '')), 120), '');

    if quantity_value < 1 or quantity_value > 99 then
      raise exception 'invalid_quantity';
    end if;

    select *
    into product_record
    from public.products
    where id = product_id_value
      and is_active = true
    for update;

    if not found then
      raise exception 'product_unavailable';
    end if;

    if product_record.stock < quantity_value then
      raise exception 'insufficient_stock';
    end if;

    line_total_value := product_record.price * quantity_value;
    subtotal_value := subtotal_value + line_total_value;

    update public.products
    set stock = stock - quantity_value
    where id = product_record.id;

    insert into public.order_items (
      order_id,
      product_id,
      product_name,
      product_slug,
      unit_price,
      quantity,
      line_total,
      selected_color,
      selected_compatibility,
      image_url
    )
    values (
      order_id_value,
      product_record.id,
      product_record.name,
      product_record.slug,
      product_record.price,
      quantity_value,
      line_total_value,
      selected_color_value,
      selected_compatibility_value,
      null
    );

    created_items := created_items || jsonb_build_object(
      'productId', product_record.id,
      'productName', product_record.name,
      'productSlug', product_record.slug,
      'unitPrice', product_record.price,
      'quantity', quantity_value,
      'lineTotal', line_total_value,
      'selectedColor', selected_color_value,
      'selectedCompatibility', selected_compatibility_value
    );
  end loop;

  update public.orders
  set
    subtotal = subtotal_value,
    total = subtotal_value + shipping_cost_value
  where id = order_id_value;

  insert into public.order_status_history (
    order_id,
    previous_status,
    new_status,
    changed_by,
    note
  )
  values (
    order_id_value,
    null,
    'pending',
    current_user_id,
    'Pedido creado desde checkout web'
  );

  return jsonb_build_object(
    'id', order_id_value,
    'orderNumber', order_number_value,
    'status', 'pending',
    'subtotal', subtotal_value,
    'shippingCost', shipping_cost_value,
    'discountAmount', 0,
    'total', subtotal_value + shipping_cost_value,
    'currency', 'ARS',
    'items', created_items
  );
end;
$$;

create or replace function public.update_order_status(
  order_id_value uuid,
  new_status_value text,
  note_value text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  previous_status_value text;
begin
  if not (select public.has_admin_access()) then
    raise exception 'not_allowed';
  end if;

  if new_status_value not in ('pending', 'confirmed', 'preparing', 'ready', 'shipped', 'delivered', 'cancelled') then
    raise exception 'invalid_status';
  end if;

  select status
  into previous_status_value
  from public.orders
  where id = order_id_value
  for update;

  if not found then
    raise exception 'order_not_found';
  end if;

  if previous_status_value = new_status_value then
    return;
  end if;

  update public.orders
  set status = new_status_value
  where id = order_id_value;

  insert into public.order_status_history (
    order_id,
    previous_status,
    new_status,
    changed_by,
    note
  )
  values (
    order_id_value,
    previous_status_value,
    new_status_value,
    (select auth.uid()),
    nullif(left(btrim(coalesce(note_value, '')), 240), '')
  );
end;
$$;

revoke execute on function public.set_order_updated_at() from public;
revoke execute on function public.set_order_updated_at() from anon;
revoke execute on function public.set_order_updated_at() from authenticated;

revoke execute on function public.create_order(jsonb) from public;
grant execute on function public.create_order(jsonb) to anon;
grant execute on function public.create_order(jsonb) to authenticated;

revoke execute on function public.update_order_status(uuid, text, text) from public;
revoke execute on function public.update_order_status(uuid, text, text) from anon;
grant execute on function public.update_order_status(uuid, text, text) to authenticated;
