import type { SVGProps } from "react";
import { Container } from "@/components/ui/container";
import { getActiveBenefits } from "@/lib/home-content/config";
import type { HomeContentBenefitIcon, HomeContentBenefits } from "@/lib/home-content/types";

function HouseIcon(props: SVGProps<SVGSVGElement>) { return <svg fill="none" stroke="currentColor" strokeWidth="1.6" viewBox="0 0 24 24" {...props}><path d="m4 10 8-6 8 6v9.5H4V10Z" strokeLinejoin="round" /><path d="M9 19.5v-5h6v5" strokeLinejoin="round" /></svg>; }
function SendIcon(props: SVGProps<SVGSVGElement>) { return <svg fill="none" stroke="currentColor" strokeWidth="1.6" viewBox="0 0 24 24" {...props}><path d="M4 7.5h10.5v9H4zM14.5 10.5H18l2 2v4h-5.5" strokeLinejoin="round" /><circle cx="7.5" cy="18" r="1.5" /><circle cx="17.5" cy="18" r="1.5" /></svg>; }
function HeartIcon(props: SVGProps<SVGSVGElement>) { return <svg fill="none" stroke="currentColor" strokeWidth="1.6" viewBox="0 0 24 24" {...props}><path d="M12 19.5s-7-4.2-7-9.2A3.8 3.8 0 0 1 12 8a3.8 3.8 0 0 1 7 2.3c0 5-7 9.2-7 9.2Z" strokeLinejoin="round" /></svg>; }
const icons: Record<HomeContentBenefitIcon, typeof HouseIcon> = { care: HouseIcon, heart: HeartIcon, send: SendIcon, shield: HouseIcon, sparkle: HouseIcon };

export function BenefitsSection({ content }: { content: HomeContentBenefits }) { const benefits = getActiveBenefits(content.items); if (!benefits.length) return null; return <section className="bg-background-alt py-12 sm:py-16"><Container><p className="vita-label">Compra con calma</p><h2 className="mt-4 max-w-xl font-display text-4xl leading-[1.06] tracking-[-0.03em] text-foreground sm:text-5xl">Información útil, sin promesas inventadas.</h2><div className="mt-10 grid divide-y divide-border border-y border-border md:grid-cols-3 md:divide-x md:divide-y-0">{benefits.map((benefit) => { const Icon = icons[benefit.icon]; return <div className="py-6 md:px-7 md:first:pl-0 md:last:pr-0" key={benefit.title}><Icon className="h-6 w-6 text-primary" /><h3 className="mt-5 font-display text-2xl text-foreground">{benefit.title}</h3><p className="mt-3 text-sm leading-6 text-secondary">{benefit.description}</p></div>; })}</div></Container></section>; }