import Image from "next/image";
import Link from "next/link";
import { Container } from "@/components/ui/container";

const editorialMoments = [
  { label: "Textiles", title: "Capas que invitan a quedarse", text: "Lino, algodón y tramas simples para los momentos de pausa." },
  { label: "Ambientes", title: "Detalles que ordenan un rincón", text: "Objetos cotidianos para hacer más propio cada espacio." },
  { label: "Materia", title: "Madera, fibras y cerámica", text: "Materiales nobles que suman calidez sin sobrecargar." },
];

export function CategoriesSection() {
  return <section className="vita-home-habitats bg-surface py-12 sm:py-16 lg:py-24"><Container><div className="grid gap-8 lg:grid-cols-[minmax(0,4fr)_minmax(0,8fr)] lg:gap-16"><div><p className="vita-label">Formas de habitar</p><h2 className="mt-4 font-display text-4xl leading-[1.06] tracking-[-0.03em] text-foreground sm:text-5xl">Una casa se construye de a poco.</h2><p className="mt-5 max-w-md text-base leading-7 text-text-secondary">Texturas, materiales y objetos para construir espacios tranquilos, a tu ritmo.</p><Link className="mt-7 inline-flex min-h-11 items-center text-sm font-semibold text-primary underline underline-offset-4 hover:text-primary-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" href="/tienda">Explorar la tienda</Link></div><div className="vita-habitat-grid grid gap-px border border-border bg-border sm:grid-cols-[1.22fr_0.89fr_0.89fr]">{editorialMoments.map((moment, index) => <Link className="group relative flex min-h-72 flex-col justify-end overflow-hidden bg-background p-6 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" href="/tienda" key={moment.label}><Image alt="Composición editorial de textiles y objetos de hogar." className="object-cover transition-transform duration-300 group-hover:scale-[1.03]" fill sizes="(min-width: 640px) 25vw, 100vw" src={["/images/vita/textiles-cushion-editorial.webp", "/images/vita/shop-hero-editorial.webp", "/images/vita/vase-candle-editorial.webp"][index]}/><div className="absolute inset-0 bg-[rgba(46,41,36,0.42)]"/><div className="relative text-white"><span className="text-xs font-semibold tracking-[0.16em] text-white/85">{moment.label}</span><h3 className="mt-3 font-display text-2xl leading-tight">{moment.title}</h3><p className="mt-3 text-sm leading-6 text-white/90">{moment.text}</p></div></Link>)}</div></div></Container></section>;
}